### ISSUE TITLE
类名初始化为啥要加上工程的名字

### ISSUE THREAD

**Issue by kyy111** [sessionCh/RxXMLY#1]
```
let clsType = NSClassFromString(projectName+"HC"+clsName+"ViewController") as! UIViewController.Type
```

projectName是什么意思？以前没这样搞过，请大神赐教

**Comment by sessionCh** [comment]
OC没有命名空间，但Swift有，所以需要加上项目名称作为前缀才能唯一标识这个类对象，给你找了篇文章，解释的很清楚，http://blog.csdn.net/longshihua/article/details/60966998

**Comment by kyy111** [comment]
谢谢了，我这边由于ProjectName带了一个“-”，在xcode里面，“-”都被转化为“_”了，调试了半天才发现，
